equinor/sdp-flux

prod/sdp-web/deployment.yaml
prod/sdp-web/ingress.yaml
prod/sdp-web/service.yaml

Prepare for migration from internal

Added sdp-web 

---

infrastructure/cert-manager.yaml
namespaces/infrastructure.yaml

They have added the webhook component so we need to do some changes.
https://cert-manager.readthedocs.io/en/latest/getting-started/webhook.html

upgrade cert-manager

---

.travis.yml

Added vanilla Kubernetes linting to Travis CI

Ci kube lint

---

custom-charts/verdaccio/.helmignore
custom-charts/verdaccio/Chart.yaml
custom-charts/verdaccio/README.md
custom-charts/verdaccio/templates/NOTES.txt
custom-charts/verdaccio/templates/_helpers.tpl
custom-charts/verdaccio/templates/configmap.yaml
custom-charts/verdaccio/templates/deployment.yaml
custom-charts/verdaccio/templates/ingress.yaml
custom-charts/verdaccio/templates/pvc.yaml
custom-charts/verdaccio/templates/service.yaml
custom-charts/verdaccio/values.yaml
prod/verdaccio/helm-release.yaml

Update verdaccio to 4.0.3

---

.travis.yml

Travis CI fix - ignore Kustomize

Travis CI 

---

base/aware/secret-template.sh
base/kustomization.yaml
base/monitoring/logging/helm-release.yaml
base/monitoring/prometheus-operator/helm-release.yaml
base/namespaces/standalone-namespaces.yaml
base/sensu/deployment.yaml
base/standalone-components/loki/helm-release.yaml

Monitoring changes.
More output from sensu backend and add Loki
Should not break anything. Just want to have a quick "up to speed" for @soofstad

Dev into prod

---

base/infrastructure/nginx-ingress.yaml
base/monitoring/oauth2-proxy/sdp/helmrelease.yaml
base/monitoring/prometheus-operator/helm-release.yaml
base/prod/oauth2-proxy-all/helmrelease.yaml
base/standalone-components/sealed-secrets/helm-release.yaml
base/standalone-components/velero/helm-release.yaml

skip prometheus-operator for now, grafana version 7 coming soon anyway, so wont use time on manual steps.

dev bumps into dev branch

---

base/aware/api-deployment.yaml
base/aware/web-deployment.yaml
base/monitoring/monitor/web/deployment.yaml
base/monitoring/release-aware/api/deployment.yaml
base/monitoring/release-aware/web/deployment.yaml
base/prod/hgir/deployment.yaml
base/prod/sdp-web/deployment.yaml

I only want this temporary in this branch, don't want to mess up helmreleases for the dev-branch.
Can revert this when the helm3 branch goes into production.

Container capabilities into testing branch

---

base/monitoring/prometheus-operator/helm-release.yaml

Grafana 7 into prod

---

base/gitlab/helm-release.yaml
dev/gitlab/helm-release-patch.yaml

First database, bump gitlab version later.

psql 11 upgrade

---

base/gitlab/minio-helm-release.yaml
dev/gitlab/helm-release-patch.yaml
dev/gitlab/ingress.yaml
prod/gitlab/ingress.yaml

Remove obsolete unicorn references (ingresses pointing to obsolete services)
Use latest minio version  - Confirmed working with both exisiting and new LFS objects.

Gitlab tweaks into prod

---

base/kustomization.yaml
base/namespaces/standalone-namespaces.yaml
base/standalone-components/kubediff/clusterrole.yaml
base/standalone-components/kubediff/crb.yaml
base/standalone-components/kubediff/kubediff-rc.yaml
base/standalone-components/kubediff/kubediff-svc.yaml
dev/kubediff/kubediff-rc.yaml
dev/kustomization.yaml

Kubediff into prod

---

base/falco/helm-release.yaml

Hide false positives
More to come likely, need to investigate further.

Falco rule tweaks into prod 1

---

base/falco/helm-release.yaml
base/monitoring/prometheus-operator/config-map-falco.yaml

Still strugling with certain rules, but some improvements.

More Falco tweaks

---

README.md
base/gitlab/helm-release.yaml
base/infrastructure/kured.yaml

Gitlab - disable shared runner into prod

---

base/monitoring/prometheus-operator/helm-release.yaml
base/monitoring/release-aware/api/deployment.yaml
base/standalone-components/cert-manager/helm-release.yaml

Existing CRDs causing issues
helm uninstall cert-manager -n cert-manager
fluxctl sync
Done
New repo for prometheus.
Old replicatset must be deleted manually.

Cert-manager major upgrade

---

base/infrastructure/kured.yaml
base/monitoring/prometheus-operator/helm-release.yaml
base/standalone-components/external-dns/helm-release.yaml
base/standalone-components/velero/helm-release.yaml
dev/velero/helm-release-patch.yaml
prod/velero/helm-release-patch.yaml

Only minor updates
All running in dev.
Cleanup velero schedules.

Bimonthly patch day

---

base/monitoring/monitor/web/deployment.yaml

Security patches
New URL for Sensu

monitor: bump to latest docker image

---

base/gitlab/helm-release.yaml
dev/gitlab/helm-release-patch.yaml
dev/hgir/deployment-patch.yaml
dev/kustomization.yaml

Fixes hgir redirect in dev
Bumps Gitlab to latest

Bump Gitlab, fix hgir dev

---

base/gitlab/minio-helm-release.yaml
base/monitoring/release-aware/api/deployment.yaml
base/oauth2/helmrelease-all.yaml
base/oauth2/helmrelease-sdp.yaml
base/standalone-components/sealed-secrets/helm-release.yaml

See https://github.com/equinor/sdp-tools/issues/257 for details and planning

Helm Stable repo updates

---

.travis.yml
base/gitlab/helm-release.yaml
base/infrastructure/kured.yaml
base/infrastructure/nginx-ingress.yaml
base/monitoring/prometheus-operator/auth-ingress.yaml
base/monitoring/prometheus-operator/helm-release.yaml
base/sensu/deployment.yaml
base/standalone-components/cert-manager/helm-release.yaml
base/standalone-components/external-dns/helm-release.yaml
base/standalone-components/loki/helm-release.yaml
base/standalone-components/sealed-secrets/helm-release.yaml
base/standalone-components/velero/helm-release.yaml

Need to apply CRDs for kube-prometheus-stack
https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
Need to apply CRD for cert-manager
https://artifacthub.io/packages/helm/cert-manager/cert-manager/1.3.1
Need to apply CRDs for sealed-secrets
https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.16.0
Deleted clusterrole 
gitlab-prometheus-server (duplicates when trying to create helm release for gitlab)
We might also need to do more in monitoring, since this namespace was deleted in dev. Hopefully we only need to update it.

Bi-monthly patching

---

base/gitlab/helm-release.yaml

Manual steps:
Remove auto-generated ingresses. remember registry as well.
Remove crb
Remove clusterrole

Bump gitlab to latest minor version

---

base/aware/ingress.yaml
base/monitoring/release-aware/api/deployment.yaml
base/monitoring/release-aware/web/deployment.yaml
dev/aware/ingress-patch.yaml
dev/kustomization.yaml

- Fixes kustomization file
- Experiment migrating to new ingress class
- Use updated release-aware version with bugfixes and security patches

Misc tweaks and updates

---

base/kustomization.yaml
base/standalone-components/verdaccio/helm-release.yaml
base/standalone-components/verdaccio/pvc.yaml

To be able to control how Helm creates PV and PVC for verdaccio

Add explisit verdaccio PVC
